title: Luke Waldron
tagline: Insight Manager and Data Science Student
description: >
  Portfolio of analytical and data science work to support my Data Science Degree.

theme: minima

author:
  name: Luke Waldron
  location: United Kingdom

markdown: kramdown
highlighter: rouge

logo: /images/selfie.jpeg

github:
  is_project_page: false

social:
  github: BP0323887
  linkedin: luke-waldron-a59b9b96

exclude:
  - README.md


