title: Luke Waldron

description: >
  Portfolio of analytical and data science work to support my Data Science Degree.

theme: minima

markdown: kramdown

logo: /images/selfie.jpeg

github:
  is_project_page: false

social:
  github: BP0323887
  linkedin: luke-waldron-a59b9b96

exclude:
  - README.md


