title: Luke Waldron
description: >
  Portfolio of analytical and data science work to support my Data Science Degree.

theme: jekyll-theme-minimal

logo: /images/selfie.jpeg
show_downloads: false

github:
  is_project_page: false

exclude:
  - README.md
